---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: ../svm-latex-statement.tex
geometry: margin = 1in
header-includes:
   - \linespread{1.1}

title: Genetische und mechanische Signalübertragung in der Organentwicklung
author: David Simon Kleinhans
affiliation: Entwicklungsbiologie der Vertebraten, Johann Wolfgang Goethe-Universität
email: "kleinhansda@gmail.com"

fontfamily: mathpazo
fontsize: 11pt
---

# Zusammenfassung

Um ein Organ zu bilden, müssen Zellen spezialisierte Funktionen und Aufgaben übernehmen. Die zelluläre Spezialisierung wird durch ein Zusammenspiel von chemischen Signalen und physi-kalischen Kräften gesteuert, wobei das eine das andere beeinflusst. Ein Aspekt der zellulären Identität ist ihre Form, die z.B. definiert, wie empfänglich die Zelle für interzelluläre Signale ist oder in welchem Abschnitt des Zellzyklus sie sich befindet und somit etwas über ihren aktuellen Zustand aussagen kann. Formveränderungen werden durch Motorproteine eingeleitet, die lokal begrenzt gesteuert und aktiviert werden. Für diese Thesis war ich daran interessiert, besser zu verstehen, wie die zelluläre Form und Geometrie die nachfolgende Zellund Organentwicklung beeinflusst. Was passiert, wenn eine Zelle nicht in eine bestimmte Form übergehen kann? Wie wirkt sich das auf die Gewebestruktur aus? Wie wirkt es sich auf die weitere Entwicklung aus? 
Ein Regulator von Motorproteinen wie dem _non-muscle_ Myosin ist Shroom3, von dem kürzlich gezeigt wurde, dass es im sich entwickelnden Seitenlinienorgan exprimiert wird und zu dessen weiterer Entwicklung beiträgt. Die Entwicklung der Seitenlinie erfolgt durch einen wandernden Cluster von anfänglich etwa 150 Zellen, das posteriore Seitenlinienprimordium (pLLP), das von vorne (Kopf) nach hinten (Schwanz) wandert und dabei Zellhaufen in einem regelmäßigen Muster ablagert. Die Literatur über die Entwicklung der Seitenlinie deutet darauf hin, dass für die Ablagerung eines Zellhaufens aus dem pLLP die Rosettenbildung eine wichtige Voraussetzung ist. Daher war unsere Erwartung an die Mutante, dass die Menge der abgelagerten Cluster _zumindest_ deutlich reduziert ist. Zu unserer Überraschung fanden wir bei der ersten Untersuchung des Seitenlinienorgan Phänotyps am Ende der Migration viele Individuen mit einer signifikanten Zunahme an abgelagerten Zellhaufen. Dies veranlasste uns, die Rolle von Shroom3 während der Rosettenbildung und die Prozesse, an denen es beteiligt ist, neu zu überdenken.\newline

Um die Auswirkungen von Shroom3 auf die Entwicklung des Seitenlinienen Organs zu untersuchen, wurde eine Mutanten-Linie generiert und mit verschiedenen transgenen Linien gekreuzt, die fluoreszenzmarkierte Proteine exprimieren, die sich an Organellen wie der Plasmamembran oder dem Zellkern lokalisieren. Anschließend wurde die Mutante mit ihren fluoreszenten Markier-ungen unter verschiedenen Bedingungen mikroskopisch abgebildet, um verschiedene zellmorphometrische Merkmale zu quantifizieren und zu analysieren. Obwohl der Zebrafisch ein beliebter Modellorganismus ist und sich hervorragend für die Entwicklungsbiologie und fortgeschrittene Mikroskopie eignet, gab es bisher keine Methoden, die eine standardisierte und stärker automatisierte Pipeline der Datenerfassung und -verarbeitung ermöglichen würden. Um die morphogenetischen Prozesse, an denen Shroom3 beteiligt ist, genau quantifizieren zu können, habe ich ein neues Toolset entwickelt, das meine Arbeit deutlich effizienter gemacht hat. Das Toolset besteht aus (1) einer neuen Methode zur Probenmontage, die auf einem 3D-Agarosegel basiert, das die Anzahl der Embryonen die auf einmal montiert und abgebildet werden können erhöht und den Bildgebungsprozess erheblich beschleunigt. (2) Für die Bildanalyse habe ich vier Programme entwickelt, die den Prozess automatisieren und somit die Ergebnisse reproduzierbarer und die Analyse deutlich effizienter machen. Das erste Programm wird für Analysen am Ende der Migration verwendet, um das Muster, die Anzahl und die Größe von Seitenlinien Zellhaufen abzuleiten. Das zweite wird nicht für _Ende der Migration_, sondern für Analysen der _Migration_ (bei Zeitrafferaufnahmen) verwendet. Außerdem bereitet es die Bilder für weitergehende Downstream-Migrationsanalysen vor und ermöglicht die Analyse des Fluoreszenzsignals auf einem zweiten Kanal. Das dritte Programm wird verwendet, um das pLLP bei hoher räumlicher Auflösung zu analysieren und um die Zellzahl, 3D-Zellmorphometrie (wie das Volumen) und die Zellorientierung zu analysieren. Das vierte Programm schließlich wird dem zweiten und dritten Programm nachgeschaltet und ist in der Lage, zelluläre Rosetten zu erkennen und mit dem Aussehen von Wildtyp-Rosetten zu vergleichen und zu gewichten.\newline

Hier zeige ich, dass in Abwesenheit von Shroom3 die Rosettenbildung im migrierenden pLLP destabilisiert ist, was zu einer verstärkten Ablagerung von Zellhaufen führt, und ich zeige, wie dies aufgrund einer möglichen Abhängigkeit der Beschleunigung und Migrationsgeschwindigkeit des pLLP mit Traktionskräften zusammenhängen könnte. Weiterhin zeige ich, dass die apikale Konstriktion und Rosettenbildung in Shroom3-defizienten Embryonen nicht blockiert ist, sondern dass größere Rosetten in viele kleinere fragmentiert werden. Schließlich gebe ich einen Ausblick darauf, wie das Fehlen von Shroom3 und das Ausbleiben der morphologischen Veränderungen die Gentranskription deregulieren kann, indem die Mengen von Atoh1a, einem für die Haarzellentwicklung notwendigen Transkriptionsfaktor, erhöht werden.\newline

Für die Probenmontage habe ich eine neue Methode entwickelt, die auf einem 3D-Agarosegel basiert und (1) die Anzahl der Embryonen, die auf
einmal montiert und abgebildet werden können, erhöht (2) schonender für die Embryonen ist und (3) den Bildgebungsprozess deutlich beschleunigt. Darüber hinaus habe ich für die subseqente Bildanalyse eine Reihe von Programmen für die 2- und 3-D-Analyse entwickelt, die den Prozess automatisieren und damit die Ergebnisse reproduzierbarer und die Analyse deutlich effizienter machen. Meine Ergebnisse und meine Methodik zeigen, wie wichtig die Morphologie bei der Steuerung von Entwicklungsprozessen ist und wie eher kleine morphologische Veränderungen auf zellulärer Ebene
die weitere Entwicklung erheblich beeinflussen können. Meine Arbeit zeigt auch, wie leistungsfähig die moderne Genetik, Mikroskopie und Bildanalyse sind und wie vielfältig sie in Bezug auf die Bandbreite der Fragen sind, die sie beantworten können. Die von mir entwickelten Methoden und Werkzeuge bilden die Grundlage für mindestens drei Viertel der von mir durchgeführten Analysen, und zusammen mit der Dokumentation und den Daten sind sie in hohem Maße reproduzierbar. In dieser Hinsicht freut es mich besonders, dass eine meiner Entwicklungen, eine verbesserte Probenvorbereitungsmethode, bereits von vielen verschiedenen Laboren auf der ganzen Welt eingesetzt wird und ihnen hilft, ihre Ergebnisse reproduzierbarer zu machen.