# Zusammenfassung {.unnumbered}

## Einleitung {-}

Die Entwicklungsbiologie untersucht den kontinuierlichen Prozess der Anpassung von Zellen an ihre sich ständig verändernde Umgebung, von der befruchteten Eizelle bis zu einem vollständigen Organismus. Um ein Organ zu bilden, müssen Zellen spezialisierte Funktionen und Aufgaben übernehmen. Die zelluläre Spezialisierung wird gesteuert indem Proteine zu bestimmten Zeiten während der Entwicklung und bei bestimmten Zelltypen unterschiedlich exprimiert werden. Die Expression der Proteine wiederrum wird durch ein Zusammenspiel von chemischen Signalen und physikalischen Kräften gesteuert, wobei das eine das andere beeinflusst. Um ein Gewebe oder ein Organ mit einer Vielzahl von spezialisierten Zellen zu bilden, ist es wichtig, dass die einzelne Zelle Informationen darüber hat, wo sie sich befindet, was ihre Nachbarn tun, wie dicht sie gepackt ist und wie die chemische Zusammensetzung ihrer Umgebung ist. Dies wird erreicht, indem sie in ständiger Rückkopplung mit ihren Nachbarzellen steht und ihre Umgebung wahrnimmt. Nachdem die Informationen verarbeitet wurden, reagiert die Zelle, indem sie die Menge der exprimierten Proteine anpasst, um sich zu vermehren oder spezialisierte Strukturen wie Flimmerhärchen oder Axone zu entwickeln. Ein Aspekt der zellulären Identität ist ihre Form, die z.B. definiert, wie empfänglich die Zelle für interzelluläre Signale ist oder in welchem Abschnitt des Zellzyklus sie sich befindet und somit etwas über ihren aktuellen Zustand aussagen kann. Die Veränderung der Zellform kann auf zwei verschiedene Arten erfolgen. (1) aktiv: Jede Zelle hat ein dynamisches Skelett, das aus einer komplexen Matrix miteinander verbundener Proteine besteht - dem Zytoskelett. Es setzt sich aus drei grundlegenden Klassen von Filamenten zusammen, die unterschiedliche physikalische Eigenschaften haben. Mikrotubuli (die starrsten), Intermediär- und Mikrofilamente (die weichsten). Motor-Proteine wie Myosin können an Aktin-Mikrofilamenten haften und diese zusammenziehen, wodurch z.B. eine Verengung des Zelldurchmessers bewirkt wird. (2) passiv: In einem Gewebe sind Zellen neben ihren einzelnen Zytoskelettelementen auf der suprazellulären Ebene über Aktin durch Adherens junctions verbunden. Wenn sich das Gewebe an einer Stelle verformt, werden dadurch auch andere, weiter entfernte Zellen verformt. Für diese Thesis war ich daran interessiert, besser zu verstehen, wie die zelluläre Form und Geometrie die nachfolgende Zell- und Organentwicklung beeinflusst. Was passiert, wenn eine Zelle nicht in eine bestimmte Form übergehen kann? Wie wirkt sich das auf die Gewebestruktur aus? Wie wirkt es sich auf die weitere Entwicklung aus?\newline

Ein bestimmter Typ von Zell-verformung ist die apikale Konstriktion, der sich durch eine aktive Verschmälerung der apikalen Oberfläche manifestiert und eine Epithelzelle flaschen- oder keilförmig statt quaderförmig erscheinen lässt. Sie wird in der Regel von mehreren Zellen innerhalb einer Epithelschicht koordiniert, die die zur Verformung eines Gewebes notwendigen Kräfte aufbringen. Epitheliale Rosetten sind radial organisierte Zellcluster innerhalb eines Epithelgewebes, deren Spitzen ein gemeinsames Zentrum berühren, ähnlich wie eine Knoblauchknospe oder ein Kuchen, der entlang seiner Mitte in Stücke geschnitten wurde. Man geht davon aus das apikale Konstriktion erdorderlich für die Bildung Epithelialer Rosetten ist.\newline

Zur Untersuchung der Embryonalentwicklung ist der Süßwasserfisch _Danio rerio_ (auch Zebrabärbling) in den letzten Jahren zu einem wichtigen Modellorganismus geworden. _D. rerio_ ist ein diploider Organismus mit einem vollständig sequenzierten Genom und ist etwa 70$\%$ homolog zu menschlichen Genen. _D. rerio_ hat einen relativ kurzen Generationswechsel von 12-16 Wochen, eine regelmäßig große Anzahl von Embryonen von 100 / Woche & Weibchen und ist relativ anspruchslos in Bezug auf den Platzbedarf für die Zucht. Außerdem bietet _D. rerio_ etablierte Methoden zur Mutagenese, zum Screening und zur Generierung transgener Linien. Da die Embryonen von Natur aus transparent sind und sich von außen entwickeln, ist es ein ideales System für mikroskopische Untersuchungen mit molekularen Farbstoffen und _Tags_, um inter- und intrazelluläre Komponenten auch tief im Gewebe sichtbar zu machen (z.B. Zellkerne oder Zellmembran-Fluoreszenz-Tags).

Zusammen mit den Fortschritten bei den bildgebenden Verfahren ermöglicht dies eine hochauflösende _in vivo_ Langzeit-Bildgebung mit hohem Durchsatz. Insbesondere die Expression von fluoreszierenden Proteinen, gewebe- oder organspezifisch, in transparenten Embryonen bietet enorme Möglichkeiten interessante und lange offene Fragen zu adressieren. In der Natur ist der Zebrabärbling in den flachen Gewässern des indischen und pakistanischen Ganges-Zuflusses zu finden. Er weist eine ovale Körperform auf und kann im Erwachsenenalter eine Länge von bis zu 5 cm erreichen.\newline

Das Seitenliniensystem ist ein mechano-sensorisches Organ, das allen aquatischen Wirbeltieren gemeinsam ist. Es ermöglicht dem Tier Wasserbewegungen wahrzunehmen und sich so zu orientieren, sowie Beute und Fressfeinde zu erkennen. Das voll entwickelte Seitenliniensystem besteht aus Hunderten von Zellhaufen, die in einem geordneten Muster über den gesamten Körper des Tieres verteilt sind. Diese Zellhaufen sind die funktionellen Untereinheiten (genannt Neuromasten) die im voll entwickelten Zustand aus Haar-, Stütz- und Mantelzellen bestehen. Um Wasserbewegungen wahrzunehmen projiziert jeder Neuromast Kino- und Stereozilien aus der Haut die bei wasserinduzierter Auslenkung Aktionspotentiale erzeugen, die über afferente Fasern weitergeleitet werden. Jeder Neuromast wird zunächst als vorläufiges Zell-aggregat von etwa 30 Zellen aus einem größeren und wandernden Zell-aggregat, dem so genannten posterioren Seitenlinien-Primordium, abgelagert.

Das posteriore Seitenlinien-Primordium delaminiert von der posterioren Seitenlinien-Placode, kaudal des Ohrs, etwa 20 Stunden nach der Befruchtung als eine Gruppe von ~100 Zellen. Nach Bildung einer mesenchymal-ähnlichen Leitregion beginnt es entlang eines Chemokin-Gradienten, der sich am horizontalen Myoseptum befindet, zur Schwanzspitze zu wandern. Um die Entwicklung eines funktionellen Seitenlinien-Organs zu gewährleisten, müssen mehrere grundlegende biologische Prozesse wie Zellmigration, Morphogenese, Proliferation und Zellpolarisation in das posteriore Seitenlinien-Primordium integriert werden.

## Zielsetzung {-}

Ein Regulator von Motorproteinen wie dem _non-muscle_ Myosin ist Shroom3, von dem kürzlich gezeigt wurde, dass es im sich entwickelnden Seitenlinienorgan exprimiert wird und zur apikalen Konstriktion und dessen weiterer Entwicklung beiträgt. Die Literatur über die Entwicklung der Seitenlinie deutet darauf hin, dass für die Ablagerung eines Zellhaufens aus dem posterioren Seitenlinien-Primordium die Rosettenbildung eine wichtige Voraussetzung ist. Daher war unsere Erwartung an die Mutante, dass die Menge der abgelagerten Zellhaufen _zumindest_ deutlich reduziert ist. Zu unserer Überraschung fanden wir bei der ersten Untersuchung des Seitenlinienorgan Phänotyps am Ende der Migration viele Individuen mit einer signifikanten Zunahme an abgelagerten Zellhaufen. Dies veranlasste uns, die Rolle von Shroom3 während der Rosettenbildung und die Prozesse, an denen es beteiligt ist, neu zu überdenken.\newline

Um die Auswirkungen von Shroom3 auf die Entwicklung des Seitenlinienen Organs zu untersuchen, wurde eine Mutanten-Linie generiert und mit verschiedenen transgenen Linien gekreuzt, die fluoreszenzmarkierte Proteine exprimieren, die sich an Organellen wie der Plasmamembran oder dem Zellkern lokalisieren. Anschließend wurde die Mutante mit ihren fluoreszenten Markierungen unter verschiedenen Bedingungen mikroskopisch abgebildet, um verschiedene zellmorphometrische Merkmale zu quantifizieren und zu analysieren.

Obwohl der Zebrafisch ein beliebter Modellorganismus ist und sich hervorragend für die Entwicklungsbiologie und fortgeschrittene Mikroskopie eignet, gab es bisher keine Methoden, die eine standardisierte und stärker automatisierte Pipeline der Datenerfassung und -verarbeitung ermöglichen würden. Um die morphogenetischen Prozesse, an denen Shroom3 beteiligt ist, genau quantifizieren zu können, wurde ein neues Toolset entwickelt, das meine Arbeit deutlich effizienter gemacht hat. Das Toolset besteht aus (1) einer neuen Methode zur Probenmontage bei der von einem 3D gedruckten Stempel ein Abdruck in einem 3D-Agarosegel hergestellt wird, das die Anzahl der Embryonen die auf einmal montiert und abgebildet werden können deutlich erhöht und den Bildgebungsprozess erheblich beschleunigt. (2) Für die anschließende Bildanalyse wurden vier Programme entwickelt, die den Quantifizierung automatisieren und somit die Ergebnisse reproduzierbarer und die Analyse deutlich effizienter machen. Das erste Programm wird für Analysen am Ende der Migration verwendet, um das Muster, die Anzahl und die Größe von Seitenlinien Zellhaufen abzuleiten. Das zweite wird nicht für das _Ende der Migration_, sondern für Analysen der _Migration_ (bei Zeitrafferaufnahmen) verwendet. Mit diesem Programm lässt sich die Migrationsgeschwindigkeit und der genaue Zeitpunkt der Ablagerung genau bestimmen. Außerdem bereitet es die Bilder für nachgeschaltete Analysen vor indem sich die zelluläre Dynamik im posterioren Seitenlinien-Primordium ohne dessen Migration beobachten lässt und ermöglicht die Analyse des Fluoreszenzsignals auf einem zweiten Kanal. Das dritte Programm wird verwendet, um das pLLP bei hoher räumlicher Auflösung in 3D zu analysieren und um die Zellzahl, 3D-Zellmorphometrie (wie das Volumen), die Zellorientierung und die apikale Konstriktion zu analysieren. Das vierte Programm schließlich wird dem zweiten und dritten Programm nachgeschaltet und ist in der Lage, zelluläre Rosetten zu erkennen und mit dem Aussehen von Wildtyp-Rosetten zu vergleichen und zu gewichten.

## Ergebnisse {-}

Nach ersten Ergebnissen zur Rolle von Shroom3 im hinteren Seitenlinien-Primordium des Zebrafisches durch Morpholino-injizierte Knockdowns hat eine ehemalige Kollegin im Labor eine Mutante generiert, um die Rolle von Shroom3 während der Morphogenese zu bestätigen und weiter zu untersuchen. Eine acht basen-paar Deletion in der SD2-Domäne wurde isoliert und als stabile Linie erhalten. Diese Mutation führt zu einem vorzeitigen STOP-Codon, das die SD2-Domäne unterbricht und dadurch die Funktion von Shroom3 hemmt.

Während die Geburtenrate einer Verteilung des Mendelschen Erbgangs folgt, haben _homozygote_ Mutanten eine verkürzte Lebensspanne von etwa 6-9 Monaten. Shroom3-Mutanten ähneln morphologisch ihren Geschwistern, jedoch scheinen ihre Kiemenklappen vergrößert, geschwollen und nicht genau stromlinienförmig mit dem Körper verbunden zu sein. Dies zeigt sich auch durch eine erhöhte Frequenz der Kiemenklappenschläge. Wie die MO-injizierten Embryonen zeigen auch die pLLP in einer ersten qualitativen Analyse des Phänotyps einen auffälligen Defekt in der Rosettenbildung. Zu unserer Überraschung jedoch war die Anzahl der am Ende der Migration abgelagerten Neuromasten in den Mutanten im Vergleich zu den Kontrollen deutlich erhöht.\newline 

Hier zeige ich, dass in Abwesenheit von Shroom3 die Rosettenbildung im migrierenden posterioren Seitenlinien-Primordium destabilisiert ist, was zu einer verstärkten Ablagerung von Zellhaufen führt, und ich zeige, wie dies aufgrund einer möglichen Abhängigkeit der Beschleunigung und Migrationsgeschwindigkeit des posterioren Seitenlinien-Primordium mit Traktionskräften zusammenhängen könnte. Weiterhin zeige ich, dass die apikale Konstriktion und Rosettenbildung in Shroom3-defizienten Embryonen nicht blockiert ist, sondern dass größere Rosetten in viele kleinere fragmentiert werden. Schließlich gebe ich einen Ausblick darauf, wie das Fehlen von Shroom3 und das Ausbleiben der morphologischen Veränderungen die Gentranskription deregulieren kann indem die Mengen von Atoh1a, einem für die Haarzellentwicklung notwendigen Transkriptionsfaktor, erhöht werden.\newline

Für die Probenmontage habe ich eine neue Methode entwickelt, die auf einem 3D-Agarosegel basiert und (1) die Anzahl der Embryonen, die auf einmal montiert und abgebildet werden können, deutlich erhöht (2) durch die optimierte Orientierung weniger häufig belichtet werden und somit schonender für die Embryonen ist und (3) den Bildgebungsprozess durch eine regelmäßige und gleichbleibende Anordnung automatisierbar und somit deutlich beschleunigt. Darüber hinaus habe ich für die anschließende Quantifizierung eine Reihe von Marko-Programmen für die 2D- und 3D-Analyse entwickelt, die den Prozess automatisieren und damit die Ergebnisse reproduzierbarer und die Analyse deutlich effizienter machen. Meine Ergebnisse und meine Methodik zeigen, wie wichtig die Morphologie bei der Steuerung von Entwicklungsprozessen ist und wie schon kleine morphologische Veränderungen auf zellulärer Ebene die weitere Entwicklung erheblich beeinflussen können. Meine Arbeit zeigt auch, wie leistungsfähig die moderne Genetik, Mikroskopie und Bildanalyse sind und wie vielfältig sie in Bezug auf die Bandbreite der Fragen sind, die sie beantworten können. Die von mir entwickelten Methoden und Werkzeuge bilden die Grundlage für mindestens drei Viertel der von mir durchgeführten Analysen, und zusammen mit der Dokumentation und den Daten sind sie in hohem Maße reproduzierbar. In dieser Hinsicht freut es mich besonders, dass eine meiner Entwicklungen, eine verbesserte Probenvorbereitungsmethode, bereits von vielen verschiedenen Laboren auf der ganzen Welt eingesetzt wird und ihnen hilft, ihre Ergebnisse reproduzierbarer zu machen.

