---
author: '**David Kleinhans**'
date: 'Frankfurt am Main, 2019'
institution: 'Johann Wolfgang Goethe-Universität'
division: 'Entwicklungsbiologie der Vertebraten'
advisor: 'Prof. Dr. Sven Klimpel'
altadvisor: 'Prof. Dr. Virginie Lecaudey'
department: 'Fachbereich Biowissenschaften'
degree: '**PhD in Biology**'
title: '**Mechano – Chemical Feedback Loops \linebreak During Vertebrate Organ Development**'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
#abstract: |
#  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.,

acknowledgements: |
  I thank...\newline
  
  \noindent my supervisors,
  
  - Prof. Dr. Virginie Lecaudey
  - Prof. Dr. Manfred Schliwa
  
  \noindent my students, 
  
  - Dmitri Baulin (M.Sc. Thesis)
  - Felix Godron (B.Sc. Thesis)
  - Andreas Ebert (B.Sc. Thesis)
  - Gelwa Helmand (B.Sc. Thesis)
  - Bianca Rodrigues Lima (Master student)
  - Ivan Alcantara (Master student)
  
  For trust shown in the process. For support and demand. for their patience, engangement and hard work.\newline
  
  \noindent And my animals, without whom this work would not have been possible.
  \vspace{0.5cm}

preface: |
  > "The most exciting time in the history of developmental biology is right now. Fueled both by new technologies and by new thought from other fields, we are exploding old notions and opening fantastic new horizons in embryology. [...]
  
  > Next, let’s discuss why developmental biology — both normal and pathological — holds such enduring fascination. I see two intertwined explanations. Obviously, it’s the ultimate personal creation story, telling each of us both where we came from and how we were constructed. Less obvious, but perhaps more tantalizing for us scientists, is the sheer complexity of the process. A single cell with a single genome can somehow create trillions of cells in hundreds of radically different types, and those cells can organize themselves into a specific form. The scale of this self-organization process is mind boggling, surely the most amazing of emergent properties."
  
  > \- John B. Wallingford, 2019^["We Are All Developmental Biologists", Developmental Cell, Vol.50, Issue 2, Jul 22, 2019]


dedication: |
  These \pageref{LastPage} pages are dedicated to YOU, the _reader_.\newline
  
  The decision to get a PhD for me was not a career option. I chose to be a scientist because _science_ because I was motivated by its ideals - autonomy, purity and freedom of presupposition (Aristotle) - to offer a solution to many wronggoings in the world. to to me meant I believed it was a reasonable way, the only way,  a better future. Today, even though we are on the verge of becoming a technocracy, society doesn't trust scientific results anymore. This has many reasons.\newline
  
  "Tell the truth. Don't blame people. Be strong. Do your best. Try hard. Forgive. Stay the course." - Bush Senior

bibliography: files/library.bib
csl: files/science.csl
lot: true
lof: true
disclosure: |
  Unless otherwise noted, all figures in this manuscript are an expression of my own creative achievement. Similarities between molecule, protein and signalling models exist and are based on well-known textbooks such as Lodish et al., Molecular Cell Biology, 5th Edt. and Scott F. Gilbert et al., Developmental Biology 11th Edt. 
#space_between_paragraphs: true
#- \usepackage{tikz}
---

```{r include_packages, include = FALSE}
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
```

```{r chunkopts, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.align='center', 
                      dev.args=list(bg="transparent"), dev='png') #, dev='pdf'
options(knitr.kable.NA = '')
library(pROC)
#library(plyr)
#library(dplyr)
#library(data.table)
library(ggplot2)
library(ggpubr)
library(pander)
library(kableExtra)
library(magrittr)
#library(ggpaired)
```
<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

# Zusammenfassung {.unnumbered}

# Summary {.unnumbered}

# List of Abbreviations {.unnumbered}

```{r abbrev, out.width = "0.95\\textwidth"}
options(knitr.kable.NA = '')
data <- read.delim("Abbreviations.txt")
knitr::kable(data, "latex", booktabs=T, col.names = c("Index", "Abbreviation", "Elaboration"), align=c('c', 'c', 'l')) %>%
  kable_styling(full_width = T, latex_options = "striped") %>%
  row_spec(0, bold = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(3, width = "10cm") %>%
  collapse_rows(columns = 1, latex_hline = "none", valign = "top") %>%
  kable_styling(font_size = 9)
  #add_header_above(c("id labels" = 2, "metrics" = 3))
#pack_rows("Group 1", 4, 7) %>%
#pack_rows("Group 2", 8, 10)
```